### ISSUE TITLE
UIWebView中播放视频，PLeakSniffer中的代码会出错

### ISSUE THREAD

**Issue by klaus01** [music4kid/PLeakSniffer#3]
Demo：https://github.com/klaus01/WebViewAndPLeakSniffer (Xcode 7.3.1)
重现方法：以上工程在模拟器中运行，点击播放按钮播放视频，出错。
出错位置：NSObject+PLeakTrack.h + 256 memcpy(buffer, attrs, len);

**Comment by wujichao** [comment]
使用 Xcode8+iOS10 无法重现这个问题

**Comment by klaus01** [comment]
确实 Xcode 8 + iOS 10 没这问题了。
